CREATE TABLE visitors (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL,
    visit_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    is_returning BOOLEAN NOT NULL,
    page_views INTEGER DEFAULT 1,
    unique_visitor BOOLEAN NOT NULL
);

CREATE TABLE metrics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    metric_name TEXT NOT NULL,
    metric_value INTEGER NOT NULL,
    recorded_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE abandonment_rate (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL,
    abandonment_time DATETIME DEFAULT CURRENT_TIMESTAMP
);